# Site settings
permalink: pretty
title: BlazeCSS - Open Source Modular CSS Framework
description: Blaze is designed to give you structure and a good starting point for your website.
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'http://blazecss.com' # the base hostname & protocol for your site
twitter_username: blazecss
version: '2.7.1'
size: '8Kb'
size_animations: '0.9kb'

# Build settings
markdown: kramdown

# Navigation
navigation-getting-started:
- text: Install
  url: /getting-started/install/

- text: Custom build
  url: /getting-started/custombuild/

- text: About
  url: /getting-started/about/


navigation-templates:
- text: Blog
  url: /templates/blog/
- text: Dashboard
  url: /templates/dashboard/
- text: Editor
  url: /templates/editor/
- text: Login
  url: /templates/login/
- text: Mail
  url: /templates/mail/


navigation-community:
- text: Forum
  url: /community/forum/


navigation-generics:
- text: Global
  url: /generics/global/


navigation-objects:
- text: Containers
  url: /objects/containers/

- text: Grid
  url: /objects/grid/

- text: Panels
  url: /objects/panels/

- text: Images
  url: /objects/images/


navigation-components:
- text: Addresses
  url: /components/addresses/

- text: Alerts
  url: /components/alerts/

- text: Badges
  url: /components/badges/

- text: Bubbles
  url: /components/bubbles/

- text: Buttons
  url: /components/buttons/

- text: Calendars
  url: /components/calendars/

- text: Cards
  url: /components/cards/

- text: Drawers
  url: /components/drawers/

- text: Headings
  url: /components/headings/

- text: Inputs
  url: /components/inputs/

- text: Lists
  url: /components/lists/

- text: Menus
  url: /components/menus/

- text: Modals
  url: /components/modals/

- text: Navs
  url: /components/navs/

- text: Overlays
  url: /components/overlays/

- text: Pagination
  url: /components/pagination/

- text: Ranges
  url: /components/ranges/

- text: Tables
  url: /components/tables/

- text: Tabs
  url: /components/tabs/

- text: Tags
  url: /components/tags/

- text: Toasts
  url: /components/toasts/

- text: Toggles
  url: /components/toggles/

- text: Trees
  url: /components/trees/

- text: Typography
  url: /components/typography/


navigation-utilities:
- text: Alignment
  url: /utilities/alignment/

- text: Boxing
  url: /utilities/boxing/